name: e_shop_desktop
description: "DBS Project"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-210.3.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.0.0
  provider: ^6.0.5
  window_manager: ^0.3.7
  uuid: ^4.1.0
  sqlite3_flutter_libs: ^0.5.17
  sqflite_common_ffi: ^2.3.0+2
  path_provider: ^2.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  desktop_notifications: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf

  assets:
    - assets/images/
